name = "slm-directory-monitor"
version = "0.1.0"
[dependencies]

[dependencies.boost]
pkg="boost"
version="1.85.0"
type="conan"
options.magic_autolink="False"
options.system_no_deprecated="False"
options.asio_no_deprecated="False"
options.header_only="False"
options.bzip2="False"
options.without_url="False"
options.lzma="False"
options.error_code_header_only="False"
options.multithreading="True"
options.without_exception="True"
options.without_test="True"
options.filesystem_use_std_fs="False"
options.visibility="hidden"
options.without_wave="True"
options.without_regex="True"
options.diagnostic_definitions="False"
options.without_math="True"
options.without_graph="True"
options.without_nowide="True"
options.without_log="True"
options.without_fiber="True"
options.without_context="True"
options.without_stacktrace="True"
options.shared="True"
options.without_coroutine="True"
options.without_cobalt="True"
options.without_serialization="True"
options.without_chrono="True"
options.segmented_stacks="False"
options.without_json="True"
options.zstd="False"
options.without_thread="True"
options.without_date_time="True"
options.without_locale="True"
options.without_mpi="True"
options.without_timer="True"
options.without_contract="True"
options.namespace_alias="False"
options.without_python="True"
options.without_program_options="True"
options.without_filesystem="False"
options.without_type_erasure="True"
options.without_iostreams="True"
options.layout="system"
options.zlib="False"
options.without_atomic="False"
options.without_graph_parallel="True"
options.without_charconv="False"
options.without_system="False"
options.namespace="boost"
options.without_container="True"
options.without_random="True"
options.filesystem_no_deprecated="False"
options.system_use_utf8="False"